name: Zip Subfolders

on:
  push:
    branches:
      - main

jobs:
  zip_subfolders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Re create zip folder
      run: |
        rm -rf zips
        mkdir zips

    - name: Create zips
      run: |
        # Loop through subfolders in src and zip them into zips
        # without adding the parent folder (src) to the zip
        cd src
        for d in */; do zip -r ../zips/"${d%/}.zip" "$d"; done


    - name: Commit and push zipped files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add zips/*
        git commit -m "Add zipped subfolders"
        git push
